name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # The logic below handles the build and release process after release-please creates a release
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build distribution
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run package

      - name: Commit dist folder
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/
          git diff --staged --quiet || git commit -m "chore: update dist folder for release ${{ steps.release.outputs.tag_name }}"
          git push origin HEAD:master
